CC = gcc
CPP = g++
CFLAGS = -g -Wall
#CPPFLAGS = C preprocessor flags
#CXXFLAGS = C++ flags
#LDFLAGS = linker flags
#LDLIBS = -lmodbus
SOURCES = lab2A.c lab2B.c
OBJS = $(SOURCES:.c=.o)
DEPS = $OBJS:.o=.d)
vpath %.c $dir $(MAKEFILE_LIST))
CPPFLAGS += -MMD -MP
all: OBJS
.PHONY: clean
clean:
	rm -f $(OBJS) $(DEPS) mtest core *.gdb
-include $(DEPS)
